### ISSUE TITLE
Option For JSON wmv-info.properties?

### ISSUE THREAD

**Issue by brcolow** [anirudhvarma12/wmv#1]
Hello,

Nice plugin =). I was wondering if you would be interested in supporting a configuration option to allow the wmv-info.properties file to be JSON encoded, as opposed to the INI style that it is now (which could still be default, of course). Another idea is XML encoded as well.

Thanks very much.

**Comment by anirudhvarma12** [comment]
Hey, thanks :) .
I chose `properties` file because Java has inbuilt methods to read from such files. However JSON/XML would be nice to have. 

Would using libraries like Gson makes sense?

**Comment by brcolow** [comment]
Gson might be a bit heavy for this use-case. In fact, pulling a dependency in at all might be a bit heavy. It may be simple enough because there will only be one level of "nesting" to just write it without any libraries. Totally up to you though =)

**Comment by anirudhvarma12** [comment]
Yeah, thats what I thought. Pulling in any library would not make sense.

**Comment by anirudhvarma12** [comment]
Options for JSON and XML have been added in [v2.1.0](https://github.com/anirudhvarma12/wmv/releases/tag/v2.1.0)
